-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 17:37:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ticketing_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketing_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketing_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ticketing_service` ;

-- -----------------------------------------------------
-- Table `ticketing_service`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`administrator` (
  `admin_index` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_id` VARCHAR(45) NOT NULL,
  `admin_pw` VARCHAR(45) NOT NULL,
  `admin_email` VARCHAR(100) NULL DEFAULT NULL,
  `admin_contact` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`admin_index`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`bidding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`bidding` (
  `bidding_index` INT(11) NOT NULL AUTO_INCREMENT,
  `current_time` DATETIME NOT NULL,
  `starting_time` DATETIME NOT NULL,
  `ticket_owner_index` INT(11) NOT NULL,
  `max_price` INT(11) NOT NULL,
  `current_price` INT(11) NOT NULL,
  `bidder_index` INT(11) NULL DEFAULT NULL,
  `ticket_id` INT(11) NOT NULL,
  `starting_price` INT(11) NOT NULL,
  PRIMARY KEY (`bidding_index`),
  CONSTRAINT `b_index`
    FOREIGN KEY (`bidding_index`)
    REFERENCES `ticketing_service`.`buyer` (`buyer_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`buyer` (
  `buyer_index` INT(11) NOT NULL AUTO_INCREMENT,
  `buyer_id` VARCHAR(45) NOT NULL,
  `b_pw` VARCHAR(45) NOT NULL,
  `buyer_email` VARCHAR(100) NULL DEFAULT NULL,
  `buyer_contact` INT(11) NULL DEFAULT NULL,
  `buyer_account` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`buyer_index`),
  UNIQUE INDEX `b_id_UNIQUE` (`buyer_id` ASC),
  UNIQUE INDEX `b_index_UNIQUE` (`buyer_index` ASC),
  UNIQUE INDEX `b_contact_UNIQUE` (`buyer_contact` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`gig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`gig` (
  `gig_index` INT(11) NOT NULL AUTO_INCREMENT,
  `gig_organizer_index` INT(11) NOT NULL,
  `gig_date` DATETIME NOT NULL,
  `gigvenue` VARCHAR(45) NULL DEFAULT NULL,
  `gig_name` VARCHAR(45) NOT NULL,
  `gig_time` DATETIME NOT NULL,
  `gig_total_seatnum` INT(11) NOT NULL,
  `pending` INT(11) NOT NULL,
  PRIMARY KEY (`gig_index`),
  CONSTRAINT `gig_organizer_index`
    FOREIGN KEY (`gig_organizer_index`)
    REFERENCES `ticketing_service`.`organizer` (`organizer_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`organizer` (
  `organizer_index` INT(11) NOT NULL AUTO_INCREMENT,
  `organizer_id` VARCHAR(45) NOT NULL,
  `organizer_pw` VARCHAR(45) NOT NULL,
  `organizer_email` VARCHAR(45) NULL DEFAULT NULL,
  `organizer_contact` INT(11) NULL DEFAULT NULL,
  `organizer_account` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`organizer_index`),
  UNIQUE INDEX `organizer_id_UNIQUE` (`organizer_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`seat` (
  `seat_index` INT(11) NOT NULL AUTO_INCREMENT,
  `gig_index` INT(11) NOT NULL,
  `section_index` INT(11) NULL DEFAULT NULL,
  `seat_location` VARCHAR(45) NULL DEFAULT NULL,
  `seat_row_index` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`seat_index`),
  INDEX `gig_idx` (`gig_index` ASC),
  INDEX `section_idx` (`section_index` ASC),
  INDEX `gig_index` (`gig_index` ASC),
  INDEX `section_index` (`section_index` ASC),
  CONSTRAINT `gig_index_idx`
    FOREIGN KEY (`gig_index`)
    REFERENCES `ticketing_service`.`gig` (`gig_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `section_index_idx`
    FOREIGN KEY (`section_index`)
    REFERENCES `ticketing_service`.`section` (`section_index`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticketing_service`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketing_service`.`section` (
  `section_index` INT(11) NOT NULL AUTO_INCREMENT,
  `gig_index` INT(11) NOT NULL,
  `seat_index` INT(11) NULL DEFAULT NULL,
  `seat_price` INT(11) NOT NULL,
  `section_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`section_index`),
  CONSTRAINT `gig_index`
    FOREIGN KEY (`gig_index`)
    REFERENCES `ticketing_service`.`gig` (`gig_index`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
